### ISSUE TITLE
Get started checklist

### ISSUE THREAD

**Issue by anfelo** [anfelo/bogota30#2]
## TODO

*Things to be decided in order to get started with the project*
- [ ] Characterize data of the app
- [ ] Decide the special features of the app
- [ ] Pick the backend framework
- [ ] Pick the frontend framework
- [ ] Choose a desing style

🎉 🙆‍♂️ 🌶
